apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-vcr2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wkzk-tenant/rhtap-demo-app/hacbs-test-project-vcr2@sha256:4e1bfcd3cac1f0ba5d730d41c403f15ca85e8a56a16b20199778f9aabec482d3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
