apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-vcr2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-vcr2
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-vcr2
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-vcr2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-vcr2
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wkzk-tenant/rhtap-demo-app/hacbs-test-project-vcr2@sha256:4e1bfcd3cac1f0ba5d730d41c403f15ca85e8a56a16b20199778f9aabec482d3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
